def configure(conf):
  conf.env.append_unique("CPPPATH", conf.env.my_inc)
  conf.env.append_unique("CPPPATH", conf.env.ndb_inc)
  conf.env.append_unique("CPPPATH", conf.env.ndb_inc + "/ndbapi")
  conf.env.append_unique("CPPPATH", "../../include/common")
  conf.env.append_unique("CPPPATH", "../../include/ndb")
  conf.env.append_unique('CXXFLAGS', ["-Wall"])
  conf.env.append_unique("LIBPATH", conf.env.my_lib)
  conf.recurse("test")

def build(ctx):  
  obj = ctx.new_task_gen("cxx", "shlib", "node_addon")
  obj.target = "ndb_adapter"
  obj.rpath = ctx.env.my_lib
  obj.lib = [ "ndbclient" , "mysqlclient"]
  
  obj.source = \
  "src/ndb/node_module.cpp " +\
  \
  "src/common/async_common.cpp " +\
  "src/common/unified_debug.cpp " +\
  "src/common/common_v8_values.cpp " +\
  \
  "src/ndb/Record.cpp " +\
  "src/ndb/DBOperationHelper.cpp " +\
  "src/ndb/IndexBoundHelper.cpp " +\
  "src/ndb/DBDictionaryImpl.cpp " +\
  "src/ndb/Record_wrapper.cpp " +\
  "src/ndb/Ndb_init_wrapper.cpp " +\
  "src/ndb/Ndb_util_wrapper.cpp " +\
  "src/ndb/Ndb_cluster_connection_wrapper.cpp " + \
  "src/ndb/Ndb_wrapper.cpp " +\
  "src/ndb/NdbError_wrapper.cpp " +\
  "src/ndb/NdbInterpretedCode_wrapper.cpp " +\
  "src/ndb/NdbScanFilter_wrapper.cpp " +\
  "src/ndb/AsyncNdbContext.cpp " +\
  "src/ndb/AsyncNdbContext_wrapper.cpp " +\
  "src/ndb/NdbTypeEncoders.cpp " +\
  "src/ndb/NdbRecordObject.cpp " +\
  "src/ndb/ColumnProxy.cpp " +\
  "src/ndb/ColumnHandler.cpp " +\
  "src/ndb/ValueObject.cpp " +\
  "src/ndb/EncoderCharset.cpp " +\
  "src/ndb/SessionImpl.cpp " +\
  "src/ndb/SessionImpl_wrapper.cpp " +\
  "src/ndb/TransactionImpl.cpp " +\
  "src/ndb/TransactionImpl_wrapper.cpp " +\
  "src/ndb/BatchImpl.cpp " +\
  "src/ndb/BatchImpl_wrapper.cpp " +\
  "src/ndb/ScanOperation.cpp " +\
  "src/ndb/ScanOperation_wrapper.cpp " +\
  "src/ndb/BlobHandler.cpp " +\
  "src/ndb/KeyOperation.cpp " +\
  "src/ndb/QueryOperation.cpp" +\
  "src/ndb/QueryOperation_wrapper.cpp" +\
  \
  "src/ndb/mysqlclient_wrapper.cpp " +\
  ""
  
  ctx.recurse("test")